modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
[[mods]]
modId = "healthcheck"
version = "${file.jarVersion}"
displayName = "Health Check"
authors = "SeraphJACK"
description = "Health check forge implementation."
